"use client";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import HeaderBackground from "./components/UI/Molecules/HeaderBackground/HeaderBackground";
import Search from "./components/UI/Molecules/Search/Search";
import { useState } from "react";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [value, setvalue] = useState("Iphon");
  const onClick = () => {
    console.log("click");
  };
  return (
    <html lang="en">
      <body className={inter.className}>
      <HeaderBackground>
        <Search
          onSearch={setvalue}
          onClick={onClick}
          placeholder="Buscando productos, marcas y más ..."
        ></Search>
      </HeaderBackground>
        {children}
      </body>
    </html>
  );
}
